config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'me', to: 'home#me'
  get 'search_books', to: 'books#search'
  resources :books, only: [:show]
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_books
  has_many :users, through: :user_books

  def self.search_books(query)
    client = Goodreads.new(api_key: Rails.application.credentials.goodreads[:key])
    client.search_books(query).results.work
  end

  def self.lookup_book(query)
    client = Goodreads.new(api_key: Rails.application.credentials.goodreads[:key])
    client.book(query)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_books
  has_many :books, through: :user_books

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    begin
      @book = Book.lookup_book(params[:id])
    rescue
      flash[:alert] = "Invalid book"
      redirect_to me_path
    end
  end

  def search
    if params[:book].present?
      @results = Book.search_books(params[:book])
      respond_to do |format|
        format.js { render partial: 'books/search_results' }
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a book to search"
        format.js { render partial: 'books/search_results' }
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    if user_signed_in?
      redirect_to me_path, turbolinks: true
    end
  end

  def me
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    err = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <ul>#{err}</ul>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_search_results.html.erb
<% if @results %>

  <ul class="container collection z-depth-3">
    <% @results.each do |result| %>
      <li id="book-search-result-container" class="collection-item hoverable brown lighten-5" data-link="<%= book_path(result.best_book.id) %>">
        <div class="row no-margin-bottom">
          <div class="col s2 m1 right-align">
            <img src=<%= result.best_book.small_image_url %> alt="" class="z-depth-2">
          </div>
          <div class="col s10 m11">
            <div class="col s12 truncate">
              <%= result.best_book.title %>
            </div>
            <div class="col s12 truncate">
              <em><%= result.best_book.author.name %></em>
            </div>
            <div class="col s12">
              <%= result.average_rating %> (<%= result.ratings_count %>)
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

<% end %>

app/views/books/_search_results.js.erb
$('#book-search-results').html('<%= j render 'books/search_results.html' %>')

// Set listeners to link results to book page
$('li[data-link]').on('click', function (e) {
    window.location = $(this).data('link')
})

app/views/books/show.html.erb
<h1>Hello From Show</h1>

<%= @book %>

app/views/home/index.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center teal-text text-lighten-2">Books Club</h1>
      <div class="row center">
        <h5 class="header col s12 light">A place to connect with others who share your love for books.</h5>
      </div>
      <div class="row center">
        <%= link_to "Get Started", new_user_registration_path, id: "download-button", class: "btn-large waves-effect waves-light teal lighten-1" %>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"><%= image_tag  "background1.jpg", id:"title-background" %></div>
</div>

<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">group_add</i></h2>
          <h5 class="center">Connect with others</h5>

          <p class="light">Add friends and see what they've read, are currently reading, and plan to read. View their must-read books and reviews to find your next read.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">local_cafe</i></h2>
          <h5 class="center">Spoiler-free book chats</h5>

          <p class="light">Whether we've come accross a major plot twist or are away from our reading corner for a bit, there are times you just want to talk about what you've read. Comfortably chat about a book you are currently reading with our spoiler-free protection. (READ MORE)</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">local_library</i></h2>
          <h5 class="center">Manage your library</h5>
          <p class="light">Keep track of your read books, update your reading progress, and plan for your future reads. Rate your previously read books and showcase your must-read books to others.</p>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="parallax"><%= image_tag  "background2.jpg" %></div>
</div>

<div class="container">
  <div class="section align-center">
    <div class="row">
      <div class="col s12 center">
        <br>
        <h4 class="center-align light"><i>“A reader lives a thousand lives before he dies. The man who never reads lives only one.”</i></h4>
        <p class="right-align"> - George R.R. Martin</p>
      </div>
    </div>

  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="parallax"><%= image_tag "background3.jpg" %></div>
</div>

<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">App Created Using</h5>
        <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>

      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      Made by <a class="brown-text text-lighten-3" href="#">Logan McNeely</a>
    </div>
  </div>
</footer>

app/views/home/me.html.erb
<nav class="brown lighten-2" role="navigation">
  <div class="nav-wrapper container">
    <%= form_tag search_books_path, remote: true, method: :get, id:"search-books" do %>
    <div class="input-field">
      <%= search_field_tag :book, params[:book], placeholder: "Search Books", id:"search" %>
      <label class="label-icon" for="search"><i class="material-icons">search</i></label>
      <i id="clear-search" class="material-icons">close</i>
    </div>
    <% end %>
  </div>
</nav>

<div id="book-search-results">
  <%= render "books/search_results" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer"> 
  <div class="footer-copyright">
    <div class="container">
      © 2020 Logan McNeely
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="brown lighten-5" role="navigation">
  <div class="nav-wrapper container">

    <%= link_to "Book Club", root_path, id:"logo-container", class:"brand-logo center" %>

    <ul class="right hide-on-med-and-down">
      <li>
        <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Log in", new_user_session_path %>
        <% end %>
      </li>
    </ul>

    <ul id="nav-mobile" class="sidenav">
      <li><a href="#">Navbar Link</a></li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="brown lighten-5">
    <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>